language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r config/requirements.txt --use-mirrors"
# # command to run tests
env:
  - DJANGO_SETTINGS_MODULE="settings"
script: ./setup.sh
